version: '3'
services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
    - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 57000:57000
    networks:
      - telemetry      

  influxdb:
    image: influxdb:1.7.11
    container_name: influxdb
    env_file: configuration.env    
    ports:
      - 8086:8086
    networks:
      - telemetry      
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - telemetry      
    volumes:
      - grafana_data:/var/lib/grafana


networks:
  telemetry:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24


volumes:
  grafana_data: {}
  influxdb_data: {}
